class OppaiWrapper:
    def __enter__(self) -> OppaiWrapper: ...
    def __exit__(self) -> None: ...
    def configure(
        self,
        mode: int,
        acc: float,
        mods: int,
        combo: int,
        nmiss: int,
    ) -> None: ...
    def calculate(self, file_path: str) -> None: ...
    def calculate_data(self, file_data: str) -> None: ...
    def get_pp(self) -> float: ...
    def get_sr(self) -> float: ...
    def set_accuracy_percent(self, acc: float) -> None: ...
    def set_combo(self, combo: int) -> None: ...
    def set_nmiss(self, nmiss: int) -> None: ...
    def set_mods(self, mods: int) -> None: ...
    def set_mode(self, mode: int) -> None: ...
